fhir:
  remote-structure-servers:
    structure01:
      url: "http://blaze:8080/fhir"

  remote-terminology-servers:
    term01:
      url: "http://terminology-service:8083/fhir"

  retrieval-page-size: 100

server:
  port: 8081

logging:
  level:
    de.uksh: debug