version: '3.8'
services:
  fhir-data-extraction:
    image: "ghcr.io/medizininformatik-initiative/fdpg-query-data-validation/extraction:0.2.9"
    environment:
      FHIR_SERVER_URL: "${FHIR_SERVER_URL:-http://localhost:8080/fhir}"
      TOTAL: "${TOTAL:-500}"
      COUNT: "${COUNT:-500}"
      VALIDATION_URL: "http://validation-mapping-service:8082/validate"
      FHIR_USERNAME: "${FHIR_USERNAME}"
      FHIR_PASSWORD: "${FHIR_PASSWORD}"
      FHIR_TOKEN: "${FHIR_TOKEN}"
      HTTP_PROXY: "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTPS_PROXY}"
      CA_FILE_NAME: "${CA_FILE_NAME}"
    volumes:
      - ${REPORT_LOCATION:-./report}:/app/report
      - ${VALIDATION_MAPPING_DIRECTORY:-./maps}:/app/maps