version: '3.8'
services:
  blaze:
    # image: "samply/blaze-upload:0.17"
    build:
      context: blaze-upload
      dockerfile: Dockerfile
    environment:
      BASE_URL: "http://blaze:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    ports:
      - "${BLAZE_PORT}:8080"
    container_name: blaze-upload
    volumes:
      - "blaze-upload-data:/app/data"
    healthcheck:
      test: curl --fail http://blaze-upload:8080/fhir || exit 1
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 5s
  termite:
    image: "ghcr.io/itcr-uni-luebeck/termite:latest"
    ports:
      - "${TERMINOLOGY_SERVICE_PORT}:8083"
    volumes:
      - terminology_data:/app/terminology_data
    container_name: terminology-service
    healthcheck:
      test: curl --fail http://terminology-service:8083/fhir/metadata || exit 1
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 5s
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
       PYTHON_DEPS: "MarkupSafe==2.0.1 aws-sam-cli==1.37.0"
       SERVICE_PORT: "${SERVICE_PORT}"
       BLAZE_PORT: "${BLAZE_PORT}"
       VALIDATOR_PORT: "${VALIDATOR_PORT}"
       PACKAGES: "${PACKAGES}"
    volumes:
      - ./profiles:/app/profiles
      - ./terminology_data:/app/terminology_data
    ports:
      - "${SERVICE_PORT}:8082"
    container_name: validation-api
    healthcheck:
      test: curl --fail http://validation-api:8082/validate || exit 1
      interval: 10s
      retries: 20
      start_period: 30s
      timeout: 10s
    depends_on:
      blaze:
        condition: service_healthy
      termite:
        condition: service_healthy
  fhir-marshal:
    image: ghcr.io/itcr-uni-luebeck/fhir-marshal:latest
    environment:
      BLAZE_PORT: "${BLAZE_PORT}"
      TERMINOLOGY_SERVICE_PORT: "${TERMINOLOGY_SERVICE_PORT}"
      VALIDATOR_PORT: "${VALIDATOR_PORT}"
      STRUCTURE_SERVER_URL: "http://blaze:8080/fhir"
      TERMINOLOGY_SERVER_URL: "http://terminology-service:8083/fhir"
      PORT: "8081"
    ports:
      - "${VALIDATOR_PORT}:8081"
    container_name: fhir-marshal
    healthcheck:
      test: 'curl -X POST http://fhir-marshal:8081/validate -H "Content-Type: application/json" || exit 1'
      interval: 5s
      retries: 20
      start_period: 20s
      timeout: 5s
    depends_on:
      web:
          condition: service_healthy
  extraction:
    build:
      context: .
      dockerfile: extraction/Dockerfile
    environment:
      FHIR_SERVER_URL: "${FHIR_SERVER_URL}"
      TOTAL: "${TOTAL}"
      COUNT: "${COUNT}"
      REPORT_LOCATION: "${REPORT_LOCATION}"
      VALIDATION_URL: "http://localhost:${SERVICE_PORT}/validate"
      USERNAME: "${USERNAME}"
      PASSWORD: "${PASSWORD}"
      FHIR_TOKEN: "${FHIR_TOKEN}"
      HTTP_PROXY: "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTPS_PROXY}"
    volumes:
      - ${REPORT_LOCATION}:/app/report
    network_mode: "host"
    container_name: extraction
    depends_on:
      fhir-marshal:
        condition: service_healthy
volumes:
  blaze-data: