version: '3.8'
services:
  blaze:
    image: "samply/blaze:0.18"
    environment:
      BASE_URL: "http://blaze:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    ports:
      - "${BLAZE_PORT}:8080"
    container_name: blaze-upload
    volumes:
      - "blaze-upload-data:/app/data"
  blaze-upload:
    image: ghcr.io/medizininformatik-initiative/fdpg-query-data-validation/blaze-upload:latest
    environment:
      BLAZE_SERVER_URL: "http://blaze:8080/fhir"
      PACKAGES: "${PACKAGES}"
    volumes:
      - profiles:/app/profiles
    container_name: blaze-upload
  termite:
    image: "ghcr.io/itcr-uni-luebeck/termite:latest"
    ports:
      - "${TERMINOLOGY_SERVICE_PORT}:8083"
    volumes:
      - terminology_data:/app/terminology_data
    container_name: terminology-service
    healthcheck:
      test: curl --fail http://terminology-service:8083/fhir/metadata || exit 1
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 5s
  fhir-marshal:
    image: ghcr.io/itcr-uni-luebeck/fhir-marshal:latest
    environment:
      BLAZE_PORT: "${BLAZE_PORT}"
      TERMINOLOGY_SERVICE_PORT: "${TERMINOLOGY_SERVICE_PORT}"
      VALIDATOR_PORT: "${VALIDATOR_PORT}"
      STRUCTURE_SERVER_URL: "http://blaze:8080/fhir"
      TERMINOLOGY_SERVER_URL: "http://terminology-service:8083/fhir"
      PORT: "8081"
    ports:
      - "${VALIDATOR_PORT}:8081"
    container_name: fhir-marshal
    healthcheck:
      test: 'curl -X POST http://fhir-marshal:8081/validate -H "Content-Type: application/json" || exit 1'
      interval: 5s
      retries: 20
      start_period: 20s
      timeout: 5s
    depends_on:
      blaze-upload:
        condition: service_completed_successfully
      termite:
        condition: service_healthy
volumes:
  blaze-data: