version: '3.8'
services:
  validation-mapping-service:
    image: "ghcr.io/itcr-uni-luebeck/validation-profile-mapper:latest"
    environment:
      SERVICE_PORT: "8082"
      VALIDATOR_URL: "http://fhir-marshal:8081/validate"
    volumes:
      - ${VALIDATION_MAPPING_DIRECTORY:-./maps}:/app/maps
    ports:
      - "${VALIDATION_MAPPING_PORT:-8092}:8082"
    container_name: validation-mapping-service