version: '3.8'
services:
  validation-mapping-service:
    image: "ghcr.io/itcr-uni-luebeck/validation-profile-mapper:0.1.15"
    environment:
      SERVICE_PORT: "8082"
      VALIDATOR_URL: "http://fhir-data-validator:8081/validate"
    volumes:
      - ${VALIDATION_MAPPING_DIRECTORY:-../maps}:/app/maps
    ports:
      - "${VALIDATION_MAPPING_PORT:-8092}:8082"