version: '3.8'
services:
  validation-structure-definition-server:
    image: "ghcr.io/samply/blaze:0.18.3"
    environment:
      BASE_URL: "http://validation-structure-definition-server:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    ports:
      - "${STRUCTURE_DEFINITION_SERVER_PORT:-8090}:8080"
    volumes:
      - "validation-structure-definition-server-data:/app/data"
    healthcheck:
      test: curl --fail http://validation-structure-definition-server:8080/health || exit 1
      interval: 5s
      retries: 20
      start_period: 20s
      timeout: 5s
  validation-structure-definition-upload:
    image: ghcr.io/medizininformatik-initiative/fdpg-query-data-validation/blaze-upload:0.3.17
    environment:
      BLAZE_SERVER_URL: "http://validation-structure-definition-server:8080/fhir"
      PACKAGES: "${SIMPLIFIER_PACKAGES}"
      # Necessary for downloading packages via proxy
      # See https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module
      HTTP_PACKAGE_DOWNLOAD_PROXY: "${HTTP_PACKAGE_DOWNLOAD_PROXY}"
      HTTPS_PACKAGE_DOWNLOAD_PROXY: "${HTTPS_PACKAGE_DOWNLOAD_PROXY}"
    volumes:
      - ${FHIR_PROFILE_DIRECTORY:-../fhir_profiles}:/app/fhir_profiles
    depends_on:
      validation-structure-definition-server:
        condition: service_healthy
  validation-terminology-service:
    image: "ghcr.io/itcr-uni-luebeck/termite:0.1.12-RC"
    ports:
      - "${TERMINOLOGY_SERVICE_PORT:-8093}:8083"
    environment:
      TERMINOLOGY_SERVICE_PORT: 8083
    volumes:
      - ${VALUE_SET_DIRECTORY:-../value_sets}:/app/value_sets
      - ${CODE_SYSTEM_DIRECTORY:-./code_systems}:/app/code_systems
    healthcheck:
      test: curl --fail http://validation-terminology-service:8083/fhir/metadata || exit 1
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 5s
  fhir-data-validator:
    image: "ghcr.io/itcr-uni-luebeck/fhir-marshal:1.1.7"
    environment:
      STRUCTURE_SERVER_URL: "http://validation-structure-definition-server:8080/fhir"
      TERMINOLOGY_SERVER_URL: "http://validation-terminology-service:8083/fhir"
      PORT: "8081"
    ports:
      - "${FHIR_DATA_VALIDATOR_PORT:-8091}:8081"
    healthcheck:
      test: 'curl -X POST http://fhir-data-validator:8081/validate -H "Content-Type: application/json" || exit 1'
      interval: 5s
      retries: 20
      start_period: 20s
      timeout: 5s
    depends_on:
      validation-structure-definition-upload:
        condition: service_completed_successfully
      validation-terminology-service:
        condition: service_healthy
volumes:
  validation-structure-definition-server-data:
    name: "validation-structure-definition-server-data"
    external: false