name: Docker

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+**

jobs:
  release-extraction:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./extraction
          tags: |
            ghcr.io/medizininformatik-initiative/fdpg-query-data-validation/extraction:latest
            ghcr.io/medizininformatik-initiative/fdpg-query-data-validation/extraction:${{ steps.prep.outputs.version }}
          push: true      
  release-blaze:
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Prepare Version
          id: prep
          run: |
            echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

        - name: Login to GitHub Docker Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: ./blaze
            tags: |
              ghcr.io/medizininformatik-initiative/fdpg-query-data-validation/blaze:latest
              ghcr.io/medizininformatik-initiative/fdpg-query-data-validation/blaze:${{ steps.prep.outputs.version }}
            push: true          
